name = "OpticalFibers"
uuid = "a66f2acf-ad95-46e9-8479-8663eca28a6d"
authors = ["Daniel Holleufer <daniel.holleufer@gmail.com>"]
version = "0.1.0"

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.12"
Bessels = "0.2.8"
Cuba = "2.3.0"
Distributions = "0.25.117"
Integrals = "4.5.0"
LinearAlgebra = "1.11.0"
NonlinearSolve = "4.4.0"
Optim = "1.11.0"
Optimization = "5.0.0"
OptimizationNLopt = "0.3.3"
Random = "1.11.0"
SpecialFunctions = "2.5.1"
